#!/bin/bash
# bootstrap.sh — agentless tai bootstrap from Host A onto Host B.
#
# Run this ON HOST A (your laptop, the one with Claude installed).
# Ships /usr/local/bin/tai + a generated launcher.command to /tmp/
# on Host B over scp, then fires `open` over ssh so the launcher
# runs inside Terminal.app on B — that gives the spawned tcsh
# listener Terminal.app's TCC attribution (so Accessibility /
# Screen Recording grants apply).
#
# Idempotent: re-run to refresh the binary or rotate the token.
#
# Usage:
#     ./bootstrap.sh user@hostB
#
# Optional env:
#     TAI_BINARY=/path/to/tai-bundled-macos-universal2   # default: /usr/local/bin/tai
#     TAI_LISTEN_PORT=7081                                # remote listen port
#     TAI_REMOTE_TOKEN_PATH=/tmp/tai-token                # where launcher writes the token on B
#     TAI_LOCAL_TOKEN_PATH=/tmp/tai-bridge-token          # local copy on A for the bridge
#
# Prereqs:
#     - SSH key-based auth to Host B (no password prompts).
#     - tai v0.1.0a38+ at TAI_BINARY (needs `tcsh --listen`).
#     - On Host B: Java installed; Terminal.app granted Accessibility
#       + Screen Recording (verifiable with `doctor`).

set -eu

TARGET=${1:-}
if [ -z "$TARGET" ]; then
    echo "Usage: $0 user@hostB" >&2
    exit 64
fi

BINARY=${TAI_BINARY:-/usr/local/bin/tai}
PORT=${TAI_LISTEN_PORT:-7081}
REMOTE_TOKEN_PATH=${TAI_REMOTE_TOKEN_PATH:-/tmp/tai-token}
LOCAL_TOKEN_PATH=${TAI_LOCAL_TOKEN_PATH:-/tmp/tai-bridge-token}

if [ ! -x "$BINARY" ]; then
    echo "ERROR: TAI_BINARY=$BINARY not found or not executable." >&2
    echo "Set TAI_BINARY to the path of your downloaded tai-bundled-macos-universal2." >&2
    exit 2
fi

TOKEN=$(uuidgen)
mkdir -p "$(dirname "$LOCAL_TOKEN_PATH")"
echo "$TOKEN" > "$LOCAL_TOKEN_PATH"
chmod 600 "$LOCAL_TOKEN_PATH"

# Generate the launcher with the token baked in. Single quotes around
# the heredoc terminator → no expansion here; we expand TOKEN/PORT
# ourselves with sed afterwards so embedded $ signs in the script
# (none today, but defensively) stay safe.
LAUNCHER=$(mktemp -t tai-launcher.XXXXXX.command)
cat > "$LAUNCHER" <<'LCMD'
#!/bin/bash
# launcher.command — runs inside Terminal.app on Host B.
# Generated by tai-ssh-bootstrap. DO NOT edit by hand; bootstrap.sh
# regenerates this on every run.
set -eu

PORT='__PORT__'
TOKEN='__TOKEN__'
REMOTE_TOKEN_PATH='__REMOTE_TOKEN_PATH__'

ln -sf /tmp/tai /tmp/tcsh
printf '%s\n' "$TOKEN" > "$REMOTE_TOKEN_PATH"
chmod 600 "$REMOTE_TOKEN_PATH"

# Kill any prior listener. It persists across sessions (serial accept
# loop), so it would still hold the port — and it carries a different
# per-session token, so it could never accept this session anyway.
pkill -f '^/tmp/tcsh --listen' >/dev/null 2>&1 || true

# Spawn the listener detached. nohup + close-stdin + bg means the
# Terminal window can close while the listener keeps running. TCC
# responsibility is set at exec() time → still Terminal.app even
# after the parent shell exits (orphan → reparented to launchd,
# but TCC responsibility is sticky).
LOG=/tmp/tai-listener.log
nohup /tmp/tcsh --listen "$PORT" --token "$TOKEN" \
    < /dev/null > "$LOG" 2>&1 &
disown

# Sanity-print so the operator (the Terminal window briefly visible
# on Host B's screen) can confirm.
echo "tai listener started on 127.0.0.1:$PORT (PID $!)"
echo "  log:    $LOG"
echo "  token:  $REMOTE_TOKEN_PATH"
echo ""
echo "Terminal window will close in ~1s. Listener stays alive."

# Auto-close THIS Terminal window after a beat. Background so it
# fires after this script's exit. The `osascript` only targets
# windows whose title contains the .command basename, so other
# Terminal sessions stay alive.
( sleep 1 && osascript -e 'tell application "Terminal" to close (every window whose name contains "launcher")' >/dev/null 2>&1 ) &
exit 0
LCMD

# Substitute baked values into the launcher template
sed -i.bak \
    -e "s|__PORT__|${PORT}|g" \
    -e "s|__TOKEN__|${TOKEN}|g" \
    -e "s|__REMOTE_TOKEN_PATH__|${REMOTE_TOKEN_PATH}|g" \
    "$LAUNCHER"
rm -f "${LAUNCHER}.bak"
chmod +x "$LAUNCHER"

echo ">>> Shipping tai binary ($(du -h "$BINARY" | cut -f1)) → $TARGET:/tmp/tai"
scp -q "$BINARY" "$TARGET":/tmp/tai

echo ">>> Shipping launcher → $TARGET:/tmp/launcher.command"
scp -q "$LAUNCHER" "$TARGET":/tmp/launcher.command

echo ">>> Setting exec bits + clearing quarantine on $TARGET"
ssh "$TARGET" \
    'chmod +x /tmp/tai /tmp/launcher.command && \
     xattr -d com.apple.quarantine /tmp/tai 2>/dev/null || true'

echo ">>> Firing launcher inside Terminal.app on $TARGET (open via Launch Services)"
ssh "$TARGET" 'open /tmp/launcher.command'

# A Terminal window briefly appears on B's screen, runs the launcher,
# spawns the detached listener, then auto-closes.

# Clean up local temp
rm -f "$LAUNCHER"

cat <<EOF

✓ Bootstrap done.

  Host B listener: 127.0.0.1:$PORT     (one session at a time; reconnectable)
  Host B token   : $REMOTE_TOKEN_PATH
  Host A token   : $LOCAL_TOKEN_PATH

Test end-to-end (manual MCP roundtrip):
    ./smoke.sh $TARGET $PORT

Plug into Claude (~/.claude.json, or per-project):
    {
      "mcpServers": {
        "tai-on-$TARGET": {
          "command": "$(pwd)/mcp-bridge.py",
          "args": ["$TARGET", "$PORT"]
        }
      }
    }
EOF
